.TH MINICLI 3
.SH NAME
minicli \- Simple CLI parser
.SH LIBRARY
libminicli, -lminicli
.SH SYNOPSIS
.In minicli.h
.SH DESCRIPTION

.SH SEE ALSO
.XR mcli_get_program_name 3 ,
.XR mcli_set_program_name 3 ,
.XR mcli_get_program_desc 3 ,
.XR mcli_set_program_desc 3 ,
.XR mcli_get_program_version 3 ,
.XR mcli_set_program_version 3 ,
.XR mcli_get_program_bugreport 3 ,
.XR mcli_set_program_bugreport 3 ,
.XR mcli_usage 3 ,
.XR mcli_version 3 ,
.XR mcli_get_argument 3
