name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install deps
        run: |
          sudo apt update
          sudo apt install build-essential
      - name: build
        run: |
          autoreconf -i -f
          ./configure
          make